//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrentItem()
        {
            this.CurrentItemCart = new HashSet<CurrentItemCart>();
            this.CurrentItemStore = new HashSet<CurrentItemStore>();
            this.PhotoItem = new HashSet<PhotoItem>();
            this.History = new HashSet<History>();
        }
    
        public int CurrentItemID { get; set; }
        public int GeneralItemID { get; set; }
        public int ColorID { get; set; }
        public int SizeID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ColorItem ColorItem { get; set; }
        public virtual GeneralItem GeneralItem { get; set; }
        public virtual SizeItem SizeItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentItemCart> CurrentItemCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentItemStore> CurrentItemStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoItem> PhotoItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
    }
}
