//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int PassportID { get; set; }
        public int EmployeeID { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public System.DateTime DateOfRelease { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
